### ISSUE TITLE
deploy on arb

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#69]
- [ ] testnet
- [ ] mainnet

**Comment by johnx25bd** [comment]
Seems important to create and use mainnet Astral deployer accounts with a high level of security (i.e. mnemonic held offline / in a hardware wallet etc) — @ronerlih, do you have a plan for this? 

(Per your comment in Slack on the importance of deploying future versions of EAS schemas with the same deployer address for easy indexing ...)
