### ISSUE TITLE
Add attestations markers on homepage map

### ISSUE THREAD

**Issue by ronerlih** [AstralProtocol/astralprotocol#95]
## 💬 Description
Get attestations from eas pgraphQL and display as markers. Stretch goal: display avatar profile pictures in marker overlays on Mapbox.

## 🗞️ Context
Relevant context to this issue-story.

## 🏗️ TO-DO (tasks or sub-issues)
- [ ]
- [ ]

## ✅ Acceptance criteria
- 
-

**Comment by johnx25bd** [comment]
Cross-posting [comment](https://github.com/AstralProtocol/eas-checkin-dapp/pull/8/commits/ff47eec8f972e739e9b4af303dace8a6cb2c0e70#r1597628940) about using the Airstack API to fetch Farcaster profile pics, if they're available.
